apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-db-deployment
  labels:
    back: post-db
spec:
  replicas: 1
  selector:
    matchLabels:
      back: post-db
  template:
    metadata:
      labels:
        back: post-db
    spec:
      containers:
      - name: post-db
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_USER
            value: "root"
          - name: MYSQL_ROOT_PASSWORD
            value: "password"
          - name: MYSQL_DATABASE
            value: "sample"
