apiVersion: apps/v1
kind: Deployment
metadata:
  # namespace: test
  name: post
  labels:
    app: post
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
      - name: post
        image: zemisemi/post
        ports:
        - containerPort: 8090
        command:
          - sh
          - -c
          - go run main.go
        # tty: true
        env:
          - name: DB_USER
            value: "root"
          - name: DB_PASSWORD
            value: "password"
          - name: DB_NAME
            value: "sample"
          - name: DB_ADDRESS
            value: "post-db:3306"
          - name: USER_URL
            value: "http://user"
          - name: POINT_URL
            value: "http://point"
